name: arc-runner
on:
  push:
    branches: ["ENGINEERING"]
jobs:

  image:
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.image.outputs.image_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Generate image version
      id: image
      run: image/image.py --filename=image/image.yaml

  build:
    runs-on: ubuntu-latest
    needs: image
    environment: ENGINEERING
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKERHUB_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.workflow }}:${{ fromJson(needs.image.outputs.image_version) }}
        context: .
