name: image
on:
  push:
    branches: ["ENGINEERING"]
jobs:

  fetch:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
    - uses: actions/checkout@v4
    - name: Generate image
      id: image
      run: python3 image/image.py --filename=image/image.yaml --mode=fetch

  build:
    runs-on: ubuntu-latest
    needs: fetch
    environment: ENGINEERING
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKERHUB_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: echo ${{ fromJSON(needs.fetch.outputs.image).repository }}
    - run: echo ${{ fromJSON(needs.fetch.outputs.image).version }}
    - run: python3 image/image.py --filename=image/image.yaml --mode=update
    - run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add image/image.yaml
        git commit -m "workflow: updated image/image.yaml via github action"
        git push

#    - uses: docker/build-push-action@v5
#      with:
#        push: true
#        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ fromJSON(needs.fetch.outputs.image).repository }}:${{ fromJSON(needs.fetch.outputs.image).version }}
#        context: .
